include: package:flutter_lints/flutter.yaml
analyzer:
  errors:
    prefer_const_constructors: ignore
    library_private_types_in_public_api: ignore
    use_build_context_synchronously: ignore
    prefer_const_literals_to_create_immutables: ignore
    unused_field: ignore
